[info]
broadcount=3		;公告数量
broadtime=300000		;公告间隔时间
huodongcount=0		;活动数量

[broad0]
contex=如果您在游戏里遇到BUG，请及时到交流群提交管理员，我们会尽快修改。如果您在游戏中体验到任何精彩之处，请向您的朋友推荐本服，我们将做得更好！

[broad1]
contex=请保护好您的#cFFA500帐号#cFF0000与#cFFA500密码#cFF0000，以免给您带来不必要的损失和麻烦。#BGM#cFF0000不会在游戏中以任何身份或者任何理由询问玩家的#cFFA500帐号密码#cFF0000，谨防受骗！

[broad2]
contex=若您在游戏中遇到任何问题，请到本服官方网站#cFF0000或者交流群#cFF0000留言，我们会尽快为您解决！

[broad3]
contex=当前服务端版本为：0.00.0001。

[broad4]
contex=服务器滚动公告

[broad5]
contex=服务器滚动公告

[broad6]
contex=服务器滚动公告

[broad7]
contex=服务器滚动公告

[broad8]
contex=服务器滚动公告

[broad9]
contex=服务器滚动公告

;---贼兵入侵活动------------------------------
;---4 太湖--场景---
[huodong0]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=52	;开始时间
			;时间控制类型＝0时：(前三位表示一年中的天数1～365，后两位表示一天时间的刻数0～95)
			;时间控制类型＝1时：(前三位无意义，后两位表示一天时间的刻数0～95)
			;时间控制类型＝2时：(前二位无意义，第三位表示星期数0=星期天;1=星期一，后两位表示一天时间的刻数0～95)
			;时间控制类型＝3时：(前二位表示本月的天数(01-31)，后两位表示一天时间的刻数0～95)
time_end=56		;结束时间
scene=4		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong1]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=60	;开始时间
			;时间控制类型＝0时：(前三位表示一年中的天数1～365，后两位表示一天时间的刻数0～95)
			;时间控制类型＝1时：(前三位无意义，后两位表示一天时间的刻数0～95)
			;时间控制类型＝2时：(前二位无意义，第三位表示星期数0=星期天;1=星期一，后两位表示一天时间的刻数0～95)
			;时间控制类型＝3时：(前二位表示本月的天数(01-31)，后两位表示一天时间的刻数0～95)
time_end=64		;结束时间
scene=4		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong2]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=68	;开始时间
			;时间控制类型＝0时：(前三位表示一年中的天数1～365，后两位表示一天时间的刻数0～95)
			;时间控制类型＝1时：(前三位无意义，后两位表示一天时间的刻数0～95)
			;时间控制类型＝2时：(前二位无意义，第三位表示星期数0=星期天;1=星期一，后两位表示一天时间的刻数0～95)
			;时间控制类型＝3时：(前二位表示本月的天数(01-31)，后两位表示一天时间的刻数0～95)
time_end=72		;结束时间
scene=4		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong3]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=76	;开始时间
			;时间控制类型＝0时：(前三位表示一年中的天数1～365，后两位表示一天时间的刻数0～95)
			;时间控制类型＝1时：(前三位无意义，后两位表示一天时间的刻数0～95)
			;时间控制类型＝2时：(前二位无意义，第三位表示星期数0=星期天;1=星期一，后两位表示一天时间的刻数0～95)
			;时间控制类型＝3时：(前二位表示本月的天数(01-31)，后两位表示一天时间的刻数0～95)
time_end=80		;结束时间
scene=4		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong4]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=84	;开始时间
			;时间控制类型＝0时：(前三位表示一年中的天数1～365，后两位表示一天时间的刻数0～95)
			;时间控制类型＝1时：(前三位无意义，后两位表示一天时间的刻数0～95)
			;时间控制类型＝2时：(前二位无意义，第三位表示星期数0=星期天;1=星期一，后两位表示一天时间的刻数0～95)
			;时间控制类型＝3时：(前二位表示本月的天数(01-31)，后两位表示一天时间的刻数0～95)
time_end=88		;结束时间
scene=4		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16
;---3 嵩山
[huodong5]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=52	;开始时间
			;时间控制类型＝0时：(前三位表示一年中的天数1～365，后两位表示一天时间的刻数0～95)
			;时间控制类型＝1时：(前三位无意义，后两位表示一天时间的刻数0～95)
			;时间控制类型＝2时：(前二位无意义，第三位表示星期数0=星期天;1=星期一，后两位表示一天时间的刻数0～95)
			;时间控制类型＝3时：(前二位表示本月的天数(01-31)，后两位表示一天时间的刻数0～95)
time_end=56		;结束时间
scene=3		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong6]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=60	;开始时间
			;时间控制类型＝0时：(前三位表示一年中的天数1～365，后两位表示一天时间的刻数0～95)
			;时间控制类型＝1时：(前三位无意义，后两位表示一天时间的刻数0～95)
			;时间控制类型＝2时：(前二位无意义，第三位表示星期数0=星期天;1=星期一，后两位表示一天时间的刻数0～95)
			;时间控制类型＝3时：(前二位表示本月的天数(01-31)，后两位表示一天时间的刻数0～95)
time_end=64		;结束时间
scene=3		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong7]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=68	;开始时间
			;时间控制类型＝0时：(前三位表示一年中的天数1～365，后两位表示一天时间的刻数0～95)
			;时间控制类型＝1时：(前三位无意义，后两位表示一天时间的刻数0～95)
			;时间控制类型＝2时：(前二位无意义，第三位表示星期数0=星期天;1=星期一，后两位表示一天时间的刻数0～95)
			;时间控制类型＝3时：(前二位表示本月的天数(01-31)，后两位表示一天时间的刻数0～95)
time_end=72		;结束时间
scene=3		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong8]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=76	;开始时间
			;时间控制类型＝0时：(前三位表示一年中的天数1～365，后两位表示一天时间的刻数0～95)
			;时间控制类型＝1时：(前三位无意义，后两位表示一天时间的刻数0～95)
			;时间控制类型＝2时：(前二位无意义，第三位表示星期数0=星期天;1=星期一，后两位表示一天时间的刻数0～95)
			;时间控制类型＝3时：(前二位表示本月的天数(01-31)，后两位表示一天时间的刻数0～95)
time_end=80		;结束时间
scene=3		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong9]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=84	;开始时间
			;时间控制类型＝0时：(前三位表示一年中的天数1～365，后两位表示一天时间的刻数0～95)
			;时间控制类型＝1时：(前三位无意义，后两位表示一天时间的刻数0～95)
			;时间控制类型＝2时：(前二位无意义，第三位表示星期数0=星期天;1=星期一，后两位表示一天时间的刻数0～95)
			;时间控制类型＝3时：(前二位表示本月的天数(01-31)，后两位表示一天时间的刻数0～95)
time_end=88		;结束时间
scene=3		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

;---5--镜湖---
[huodong10]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=52	;开始时间
time_end=56		;结束时间
scene=5		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong11]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=60	;开始时间
time_end=64		;结束时间
scene=5		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong12]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=68	;开始时间
time_end=72		;结束时间
scene=5		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong13]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=76	;开始时间
time_end=80		;结束时间
scene=5		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong14]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=84	;开始时间
time_end=88		;结束时间
scene=5		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

;---6--无量山---
[huodong15]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=52	;开始时间
time_end=56		;结束时间
scene=6		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong16]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=60	;开始时间
time_end=64		;结束时间
scene=6		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong17]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=68	;开始时间
time_end=72		;结束时间
scene=6		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong18]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=76	;开始时间
time_end=80		;结束时间
scene=6		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong19]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=84	;开始时间
time_end=88		;结束时间
scene=6		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


;---7--剑阁---
[huodong20]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=52	;开始时间
time_end=56		;结束时间
scene=7		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong21]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=60	;开始时间
time_end=64		;结束时间
scene=7		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong22]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=68	;开始时间
time_end=72		;结束时间
scene=7		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong23]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=76	;开始时间
time_end=80		;结束时间
scene=7		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong24]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=84	;开始时间
time_end=88		;结束时间
scene=7		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


;---8--敦煌---
[huodong25]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=52	;开始时间
time_end=56		;结束时间
scene=8		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong26]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=60	;开始时间
time_end=64		;结束时间
scene=8		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong27]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=68	;开始时间
time_end=72		;结束时间
scene=8		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16


[huodong28]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=76	;开始时间
time_end=80		;结束时间
scene=8		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16

[huodong29]
opt_type=1		;活动执行类型：0表示仅执行一次，1表示在时间范围内每次服务器启动都会执行一次
time_type=1		;时间控制类型：0表示仅执行一次，1表示每天执行一次，2表示每周执行一次，3表示每月执行一次
time_start=84	;开始时间
time_end=88		;结束时间
scene=8		;-1表示所有场景都要激活
scriptid=050016		;活动执行的脚本,缺省调用OnDefaultEvent
param0=11
param1=12
param2=13
param3=14
param4=15
param5=16